name: "Run FibBot Action"

on:
  pull_request_target:
    types: [opened, edited, synchronize]
    branches:
      - main

permissions: write-all
   

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Event Context
        run: echo "${{ toJson(github.event) }}"

      - name: Get PR Number
        id: pr-number
        run: |
          if [ -n "${{ github.event.pull_request.number }}" ]; then
            echo "PR Number: ${{ github.event.pull_request.number }}"
            echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          else
            echo "::error::No PR number found. Running on push event."
            exit 1
          fi

      - name: Run FibBot
        id: inputs
        uses: ./
        with:
          enable_fib: true
          max_threshold: '100'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ env.pr_number }}

      - name: Debug Logs
        if: ${{ always() }}
        run: |
          echo "Job status: ${{ job.status }}"
          echo "PR Number: ${{ env.pr_number }}"

      - name: Grant Public Access to Comments
        run: |
          gh api -X PUT \
            -H "Accept: application/vnd.github.v3+json" \
            repos/${{ github.repository }}/actions/permissions/workflow -f enabled=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}