name: "Run FibBot Action"
on: [push]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run FibBot
        id: inputs
        uses: ./
        with:
          enable_fib: false
          max_threshold: '1000'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}